import {scs, validate} from "./src/scs.ts";



const values: Map<string, { count: number, example: string[], pinnedWords: string[]}> = new Map();
const perms = permutator(["maven","hold","moon","mark","jack","spark","poor","apple","solid","live"])
for(let i = 0; i < perms.length; i++) {
    if(i % 100000 === 0) {
        console.log('Progress', i, 'of', perms.length, '(', Math.floor(i / perms.length * 100), '%)');
    }
    const result = scs(perms[i]);
    if(result.length != 19) {
        console.log('Error', result.length, 'for', perms[i]);
    }
    validate(result, perms[i]);
    const existing = values.get(result);
    if(!existing) {
        values.set(result, { count: 1, example: perms[i], pinnedWords: perms[i] });
    } else {
        existing.count++;
        existing.pinnedWords = findCommon(existing.example, perms[i]);
    }
}

console.log('Found', values.size, 'unique results');
for(let [key, value] of [...values.entries()].sort((a, b) => a[1].count - b[1].count)) {
    console.log(`${key}\t${value.count}\t${JSON.stringify(value.example)}\t${JSON.stringify(value.pinnedWords)}`);
}

function findCommon(valuesA: string[], valuesB: string[]) {
    if(valuesA.length != valuesB.length) {
        throw new Error('Values must be the same length');
    }

    const common = [...valuesA];
    for(let i = 0; i < common.length; i++) {
        if(valuesA[i] !== valuesB[i]) {
            common[i] = '-';
        }
    }
    return common;
}

function permutator<T>(inputArr: T[]): T[][] {
    const results: T[][] = [];

    function permute(arr: T[], memo?: T[]): T[][] {
        let cur;
        memo = memo || [];

        for (var i = 0; i < arr.length; i++) {
            cur = arr.splice(i, 1);
            if (arr.length === 0) {
                results.push(memo.concat(cur));
            }
            permute(arr.slice(), memo.concat(cur));
            arr.splice(i, 0, cur[0]);
        }

        return results;
    }

    return permute(inputArr);
}

/*  
Found 487 unique results
jmspappholiveorckdn     12      ["live","poor","jack","mark","spark","apple","hold","maven","moon","solid"]     ["live","poor","jack","mark","spark","apple","-","-","-","-"]
jmspappholiveonrckd     20      ["live","moon","poor","jack","maven","mark","spark","apple","hold","solid"]     ["live","moon","poor","jack","-","-","-","-","hold","-"]
jmspappholiveornckd     20      ["live","poor","moon","jack","maven","mark","spark","apple","hold","solid"]     ["live","poor","moon","jack","-","-","-","-","hold","-"]
shjmapopliveaorcknd     28      ["live","spark","jack","maven","mark","solid","hold","poor","moon","apple"]     ["live","spark","jack","-","-","solid","-","-","-","-"]
hsmjapoplivecoarknd     34      ["live","jack","maven","hold","mark","apple","solid","moon","poor","spark"]     ["live","jack","-","-","-","-","-","moon","poor","spark"]
shmjapoplivecoarknd     34      ["live","jack","maven","mark","solid","hold","moon","poor","spark","apple"]     ["live","jack","-","-","solid","-","-","-","-","-"]
jspmappholiveonrckd     40      ["live","moon","poor","jack","spark","maven","mark","apple","hold","solid"]     ["live","moon","poor","jack","spark","-","-","-","hold","-"]
jspmappholiveornckd     40      ["live","poor","moon","jack","spark","maven","mark","apple","hold","solid"]     ["live","poor","moon","jack","spark","-","-","-","hold","-"]
shjmapoplivecoarknd     62      ["live","jack","maven","mark","solid","hold","poor","moon","spark","apple"]     ["live","jack","-","-","solid","-","-","-","spark","-"]
shjmapoplivedoarnck     64      ["live","solid","hold","poor","moon","jack","maven","mark","spark","apple"]     ["live","solid","-","-","-","-","-","-","-","-"]
jspmappholiveorckdn     72      ["live","poor","jack","spark","mark","apple","hold","maven","moon","solid"]     ["live","poor","jack","spark","-","-","-","-","-","-"]
hjmaspoplivedaorckn     80      ["live","hold","apple","spark","jack","maven","mark","poor","moon","solid"]     ["live","hold","apple","spark","-","-","-","-","moon","-"]
spjmappholiveornckd     80      ["live","poor","moon","spark","jack","maven","mark","apple","hold","solid"]     ["live","poor","moon","spark","-","-","-","-","hold","-"]
hjmaspopliveoarnckd     90      ["live","poor","moon","jack","maven","hold","mark","apple","spark","solid"]     ["live","poor","moon","jack","-","hold","-","apple","spark","-"]
hmjaspopliveaorcknd     96      ["live","mark","maven","hold","moon","jack","apple","spark","poor","solid"]     ["live","mark","-","-","-","-","-","-","-","-"]
jmspappholivecorkdn     96      ["live","jack","mark","spark","poor","apple","hold","maven","moon","solid"]     ["live","jack","-","-","-","apple","-","-","-","-"]
mjspappholiveorckdn     108     ["live","mark","jack","spark","poor","apple","hold","maven","moon","solid"]     ["live","-","-","-","-","apple","-","-","-","-"]
mjspappholiveornckd     108     ["live","poor","maven","moon","mark","jack","spark","apple","hold","solid"]     ["live","poor","-","-","-","-","-","-","hold","-"]
shmjapopliveoarcknd     120     ["live","mark","maven","jack","solid","hold","moon","poor","spark","apple"]     ["live","mark","-","-","solid","-","-","poor","spark","-"]
hjmaspoplivecaorknd     120     ["live","jack","maven","hold","mark","apple","spark","poor","moon","solid"]     ["live","jack","-","-","-","-","-","-","-","-"]
hsjmapopliveoarndck     120     ["live","poor","moon","hold","jack","maven","mark","spark","apple","solid"]     ["live","poor","moon","hold","-","-","-","-","-","-"]
hjmaspopliveoarndck     120     ["live","poor","moon","hold","jack","maven","mark","apple","spark","solid"]     ["live","poor","moon","hold","-","-","-","-","-","-"]
jmspappholiveorcknd     128     ["live","poor","jack","maven","moon","mark","spark","apple","hold","solid"]     ["live","poor","jack","-","-","-","-","-","hold","-"]
jmspappholiveoncrkd     140     ["live","moon","jack","maven","mark","spark","poor","apple","hold","solid"]     ["live","moon","jack","-","mark","spark","-","-","hold","-"]
hsjmapopliveoardnck     140     ["live","poor","hold","moon","jack","maven","mark","spark","apple","solid"]     ["live","poor","hold","-","-","-","-","-","-","-"]
spmjappholiveornckd     160     ["live","poor","moon","spark","maven","mark","jack","apple","hold","solid"]     ["live","poor","moon","spark","-","-","-","-","hold","-"]
shjmapoplivecaorknd     162     ["live","jack","maven","mark","spark","solid","hold","poor","moon","apple"]     ["live","jack","-","mark","-","solid","-","-","-","-"]
hmjaspoplivecaorknd     178     ["live","jack","maven","hold","moon","mark","apple","spark","poor","solid"]     ["live","jack","-","-","-","-","-","-","-","-"]
hsmjapoplivecaorknd     190     ["live","jack","maven","hold","mark","spark","apple","solid","moon","poor"]     ["live","jack","-","-","-","-","-","-","moon","poor"]
shmjapoplivecaorknd     190     ["live","jack","maven","mark","spark","solid","hold","moon","poor","apple"]     ["live","jack","-","mark","-","solid","-","-","-","-"]
smhjapoplivedcoarkn     192     ["live","solid","jack","maven","moon","hold","mark","poor","spark","apple"]     ["live","solid","-","-","-","-","-","poor","spark","-"]
hjmaspopliveoardnck     196     ["live","poor","hold","moon","jack","maven","mark","apple","spark","solid"]     ["live","poor","hold","-","-","-","-","-","-","-"]
hsmjapoplivecoarkdn     198     ["live","jack","hold","maven","mark","apple","solid","moon","poor","spark"]     ["live","jack","-","-","-","apple","-","-","-","-"]
shmjapoplivecoarkdn     198     ["live","jack","mark","solid","maven","hold","moon","poor","spark","apple"]     ["live","jack","-","-","-","hold","moon","poor","spark","-"]
smhjapoplivecoarkdn     198     ["live","jack","mark","solid","maven","moon","hold","poor","spark","apple"]     ["live","jack","-","-","-","moon","hold","poor","spark","-"]
hsjmapoplivedoarnck     204     ["live","hold","poor","moon","jack","maven","mark","spark","apple","solid"]     ["live","hold","-","-","-","-","-","-","-","-"]
jspmappholiveorcknd     208     ["live","poor","jack","moon","spark","maven","mark","apple","hold","solid"]     ["live","poor","jack","-","-","-","-","-","hold","-"]
hjmaspopliveoarcknd     210     ["live","poor","jack","maven","hold","moon","mark","apple","spark","solid"]     ["live","poor","jack","-","-","-","-","apple","spark","-"]
hmjaspoplivecaorkdn     214     ["live","jack","hold","maven","moon","mark","apple","spark","poor","solid"]     ["live","jack","-","-","-","-","-","-","-","-"]
smhjapoplivecoarknd     218     ["live","jack","maven","moon","mark","solid","hold","poor","spark","apple"]     ["live","jack","-","moon","-","-","hold","poor","spark","-"]
hsjmapopliveoarnckd     230     ["live","poor","moon","jack","maven","hold","mark","spark","apple","solid"]     ["live","poor","moon","-","-","-","-","-","apple","-"]
shjmapoplidveoarnck     240     ["solid","hold","apple","poor","moon","jack","maven","mark","spark","live"]     ["solid","-","apple","-","-","-","-","-","-","-"]
hmjaspopliveaorckdn     240     ["live","mark","hold","maven","moon","jack","apple","spark","poor","solid"]     ["live","mark","-","-","-","-","-","-","-","-"]
smhjapopliveoarckdn     240     ["live","mark","jack","solid","maven","moon","hold","poor","spark","apple"]     ["live","mark","-","-","-","moon","hold","poor","spark","-"]
sjmaphopliveoarndck     240     ["live","poor","moon","solid","hold","jack","maven","mark","spark","apple"]     ["live","poor","moon","solid","-","-","-","mark","-","-"]
smhjapoplivedoarckn     240     ["live","solid","mark","maven","moon","hold","jack","poor","spark","apple"]     ["live","solid","-","-","-","-","-","poor","spark","-"]
hjmaspoplivedoarnck     244     ["live","hold","poor","moon","jack","maven","mark","apple","spark","solid"]     ["live","hold","-","-","-","-","-","-","-","-"]
shjmapoplivedoarckn     256     ["live","solid","hold","poor","jack","maven","moon","mark","spark","apple"]     ["live","solid","-","-","-","-","-","mark","-","-"]
hmsjapoplivedcoarkn     262     ["live","hold","jack","maven","moon","mark","poor","spark","apple","solid"]     ["live","hold","-","-","-","-","-","-","-","-"]
smhjapopliveoarcknd     264     ["live","mark","maven","moon","jack","solid","hold","poor","spark","apple"]     ["live","mark","-","moon","-","-","hold","poor","spark","-"]
hmjaspoplivedcoarkn     266     ["live","hold","jack","maven","moon","mark","poor","apple","spark","solid"]     ["live","hold","-","-","-","-","poor","-","spark","-"]
hmjaspoplivecoarkdn     266     ["live","jack","hold","maven","moon","mark","poor","apple","spark","solid"]     ["live","jack","-","-","-","-","poor","-","spark","-"]
hmjaspoplivedcaorkn     274     ["live","hold","jack","maven","moon","mark","apple","spark","poor","solid"]     ["live","hold","-","-","-","mark","-","-","-","-"]
sjmaphooarplivednck     280     ["poor","live","hold","moon","jack","maven","mark","spark","apple","solid"]     ["poor","live","-","moon","-","-","-","-","-","-"]
jspmappholiveoncrkd     280     ["live","moon","jack","spark","maven","mark","poor","apple","hold","solid"]     ["live","moon","jack","-","-","-","-","-","hold","-"]
hmsjapoplivecoarkdn     286     ["live","jack","hold","maven","moon","mark","poor","spark","apple","solid"]     ["live","jack","-","-","-","-","-","-","-","-"]
hsmjapoplivedcoarkn     312     ["live","hold","jack","maven","mark","apple","solid","moon","poor","spark"]     ["live","hold","-","-","-","-","-","-","-","-"]
shmjapoplivedcoarkn     312     ["live","solid","hold","jack","maven","moon","mark","poor","spark","apple"]     ["live","solid","-","jack","-","-","-","poor","spark","-"]
sjmaphopliveoarnckd     320     ["live","poor","moon","jack","maven","mark","spark","solid","hold","apple"]     ["live","poor","moon","-","-","-","-","-","hold","-"]
shmjapoplivedoarnck     320     ["live","solid","hold","poor","maven","moon","mark","jack","spark","apple"]     ["live","solid","-","-","-","moon","-","-","-","-"]
hmjaspopliveoarnckd     330     ["live","poor","maven","moon","mark","hold","jack","apple","spark","solid"]     ["live","poor","-","-","-","hold","-","apple","spark","-"]
shjmapoplidoarvenck     336     ["solid","hold","poor","moon","jack","maven","mark","spark","apple","live"]     ["solid","hold","poor","-","-","-","-","-","-","-"]
shmjapopliveoncarkd     336     ["live","maven","jack","mark","spark","solid","hold","moon","poor","apple"]     ["live","maven","jack","-","-","-","-","-","poor","-"]
sjmaphopliveoardnck     336     ["live","poor","solid","hold","moon","jack","maven","mark","spark","apple"]     ["live","poor","solid","-","moon","-","-","mark","-","-"]
smjaphoplivedcoarkn     336     ["live","solid","jack","maven","moon","mark","poor","hold","spark","apple"]     ["live","solid","-","-","-","-","poor","-","-","-"]
shjmapoplivecoarkdn     354     ["live","jack","mark","solid","maven","hold","poor","moon","spark","apple"]     ["live","jack","-","-","-","hold","poor","-","-","-"]
smjaphoplivecoarkdn     354     ["live","jack","mark","solid","maven","moon","poor","hold","spark","apple"]     ["live","jack","-","-","-","moon","poor","-","-","-"]
hmsjapoplivedoarckn     366     ["live","hold","mark","maven","moon","jack","poor","spark","apple","solid"]     ["live","hold","-","-","-","-","-","-","-","-"]
hsjmapoplidveoarnck     380     ["hold","apple","solid","poor","moon","jack","maven","mark","spark","live"]     ["hold","-","solid","-","-","-","-","-","-","-"]
shjmapoplidoarveckn     384     ["solid","hold","poor","apple","jack","maven","moon","mark","spark","live"]     ["solid","hold","poor","-","-","-","-","mark","-","-"]
smhjapoplidvecoarkn     384     ["solid","apple","jack","maven","moon","hold","mark","poor","spark","live"]     ["solid","-","-","-","-","-","-","poor","spark","-"]
hmsjapopliveoarckdn     384     ["live","mark","hold","maven","moon","jack","poor","spark","apple","solid"]     ["live","mark","-","-","-","-","-","-","-","-"]
sjmaphoplivedoarnck     384     ["live","solid","poor","hold","moon","jack","maven","mark","spark","apple"]     ["live","solid","-","-","moon","-","-","mark","-","-"]
hjmaspoplivecoarknd     400     ["live","jack","maven","hold","mark","poor","moon","apple","spark","solid"]     ["live","jack","-","-","-","-","-","apple","spark","-"]
sjmaphopliveaorcknd     400     ["live","spark","jack","maven","mark","poor","moon","solid","hold","apple"]     ["live","spark","-","-","mark","-","-","-","hold","-"]
hmjaspoplivecoarknd     406     ["live","jack","maven","hold","moon","mark","poor","apple","spark","solid"]     ["live","jack","-","-","-","-","-","apple","spark","-"]
hsmjapopliveonardck     420     ["live","maven","poor","hold","moon","mark","jack","spark","apple","solid"]     ["live","maven","poor","-","-","-","-","-","-","-"]
shjmapopliveaorckdn     420     ["live","spark","jack","mark","solid","maven","hold","poor","moon","apple"]     ["live","spark","-","-","-","-","hold","poor","moon","-"]
hjmaspopliveoarckdn     420     ["live","poor","jack","hold","maven","moon","mark","apple","spark","solid"]     ["live","poor","jack","-","-","-","-","-","-","-"]
hsjmapopliveaorcknd     428     ["live","spark","jack","maven","hold","mark","poor","moon","apple","solid"]     ["live","spark","-","-","-","-","-","-","apple","-"]
mspjappholiveornckd     432     ["live","poor","maven","moon","mark","spark","jack","apple","hold","solid"]     ["live","poor","-","-","-","-","-","-","hold","-"]
hjmaspoplivedcaorkn     440     ["live","hold","jack","maven","mark","apple","spark","poor","moon","solid"]     ["live","hold","-","-","-","-","spark","-","moon","-"]
hjmaspoplivecaorkdn     440     ["live","jack","hold","maven","mark","apple","spark","poor","moon","solid"]     ["live","jack","-","-","-","apple","spark","-","moon","-"]
hmsjapoplidvecoarkn     454     ["hold","apple","jack","maven","moon","mark","solid","poor","spark","live"]     ["hold","-","-","-","-","-","solid","poor","spark","-"]
hsjmapoplivecoarknd     462     ["live","jack","maven","hold","mark","poor","moon","spark","apple","solid"]     ["live","jack","-","-","-","-","-","-","apple","-"]
shmjapoplidoarveckn     480     ["solid","hold","poor","apple","mark","maven","moon","jack","spark","live"]     ["solid","hold","poor","-","-","-","-","jack","-","-"]
smhjapoplidveoarckn     480     ["solid","apple","mark","maven","moon","hold","jack","poor","spark","live"]     ["solid","-","-","-","-","-","-","poor","spark","-"]
shjmapoplivedaorckn     480     ["live","solid","hold","spark","jack","maven","mark","poor","moon","apple"]     ["live","solid","-","spark","jack","-","-","poor","moon","-"]
shmjapopliveondcark     490     ["live","maven","solid","hold","moon","jack","mark","spark","poor","apple"]     ["live","maven","solid","-","-","-","mark","-","poor","-"]
hmsjapoplivecoarknd     490     ["live","jack","maven","hold","moon","mark","poor","spark","apple","solid"]     ["live","jack","-","-","-","-","-","-","apple","-"]
shjmapoplivedcoarkn     536     ["live","solid","hold","jack","maven","mark","poor","moon","spark","apple"]     ["live","solid","-","jack","-","-","poor","-","-","-"]
hmsjapopliveonardck     540     ["live","maven","moon","poor","hold","mark","jack","spark","apple","solid"]     ["live","-","-","-","-","-","-","-","-","-"]
jspmappholivecorkdn     576     ["live","jack","spark","mark","poor","apple","hold","maven","moon","solid"]     ["live","jack","-","-","-","-","-","-","-","-"]
hmjaspoplidvecoarkn     602     ["hold","apple","jack","maven","moon","mark","poor","spark","solid","live"]     ["hold","-","-","-","-","-","poor","-","-","-"]
hmsjapoplidveoarckn     606     ["hold","apple","mark","maven","moon","jack","solid","poor","spark","live"]     ["hold","-","-","-","-","-","solid","poor","spark","-"]
hsmjapopliveondcark     610     ["live","maven","hold","jack","mark","spark","poor","moon","apple","solid"]     ["live","maven","hold","-","-","-","poor","-","-","-"]
hmjaspoplivedaorckn     610     ["live","hold","mark","maven","moon","jack","apple","spark","poor","solid"]     ["live","hold","-","-","-","-","-","-","-","-"]
smjaphoplivedcaorkn     624     ["live","solid","jack","maven","moon","mark","spark","poor","hold","apple"]     ["live","solid","-","-","-","mark","-","poor","hold","-"]
hjmaspoplidveoarnck     628     ["hold","apple","poor","moon","jack","maven","mark","spark","solid","live"]     ["hold","-","-","-","-","-","-","-","-","-"]
hsjmapopliveoarcknd     638     ["live","poor","jack","maven","hold","moon","mark","spark","apple","solid"]     ["live","poor","-","-","-","moon","-","-","apple","-"]
hjmaspoplivedcoarkn     640     ["live","hold","jack","maven","mark","poor","moon","apple","spark","solid"]     ["live","hold","-","-","-","-","-","-","-","-"]
spjmappholiveonrckd     640     ["live","moon","spark","jack","maven","mark","poor","apple","hold","solid"]     ["live","moon","-","-","-","-","-","-","hold","-"]
sjmaphoplivedaorckn     640     ["live","solid","spark","jack","maven","mark","poor","hold","moon","apple"]     ["live","solid","-","-","-","-","-","-","-","-"]
hjmaspopliveoardckn     644     ["live","poor","hold","jack","maven","moon","mark","apple","spark","solid"]     ["live","poor","hold","-","-","-","-","-","-","-"]
mjspappholiveorcknd     648     ["live","mark","maven","moon","jack","spark","poor","apple","hold","solid"]     ["live","-","-","-","-","-","-","-","hold","-"]
mspjappholiveorckdn     648     ["live","mark","spark","jack","poor","apple","hold","maven","moon","solid"]     ["live","-","-","-","-","-","-","-","-","-"]
smjaphoplidvecoarkn     672     ["solid","apple","jack","maven","moon","mark","poor","hold","spark","live"]     ["solid","-","-","-","-","-","poor","-","-","-"]
hmjaspopliveondcark     672     ["live","maven","hold","moon","jack","mark","poor","apple","spark","solid"]     ["live","-","hold","-","jack","-","-","-","-","-"]
shmjapopliveonarckd     672     ["live","maven","mark","jack","spark","solid","hold","moon","poor","apple"]     ["live","maven","-","-","-","-","-","-","poor","-"]
smjaphoplivecoarknd     678     ["live","jack","maven","moon","mark","poor","spark","solid","hold","apple"]     ["live","jack","-","moon","-","-","-","-","hold","-"]
hsmjapopliveoardnck     700     ["live","poor","hold","maven","moon","mark","jack","spark","apple","solid"]     ["live","poor","hold","-","moon","-","-","-","-","-"]
hmjaspopliveoardckn     700     ["live","poor","hold","mark","maven","moon","jack","apple","spark","solid"]     ["live","poor","hold","-","-","-","-","-","-","-"]
hsjmapopliveoardckn     700     ["live","poor","hold","jack","maven","moon","mark","spark","apple","solid"]     ["live","poor","hold","-","-","-","-","-","-","-"]
hjmaspoplidveaorckn     720     ["hold","apple","spark","jack","maven","mark","poor","moon","solid","live"]     ["hold","-","-","-","-","-","-","-","-","-"]
shmjapopliveoarckdn     720     ["live","mark","jack","solid","maven","hold","moon","poor","spark","apple"]     ["live","mark","-","-","-","hold","-","-","-","-"]
hsmjapopliveoarndck     720     ["live","poor","maven","hold","moon","mark","jack","spark","apple","solid"]     ["live","poor","-","hold","-","-","-","-","-","-"]
hmjaspopliveoarndck     720     ["live","poor","maven","hold","moon","mark","jack","apple","spark","solid"]     ["live","poor","-","hold","-","-","-","-","-","-"]
hmjaspoplivedoncark     732     ["live","hold","maven","moon","jack","mark","poor","apple","spark","solid"]     ["live","hold","-","moon","jack","-","-","-","-","-"]
hmsjapopliveoarcknd     736     ["live","mark","maven","hold","moon","jack","poor","spark","apple","solid"]     ["live","mark","-","-","-","-","-","-","apple","-"]
shmjapopliveaorcknd     748     ["live","mark","maven","jack","spark","solid","hold","moon","poor","apple"]     ["live","-","-","-","-","solid","-","-","-","-"]
hsjmapoplivedcoarkn     760     ["live","hold","jack","maven","mark","poor","moon","spark","apple","solid"]     ["live","hold","-","-","-","poor","-","spark","-","-"]
hsmjapopliveoncarkd     763     ["live","maven","jack","hold","mark","spark","poor","moon","apple","solid"]     ["live","maven","jack","-","-","-","-","-","-","-"]
shjmapoplivecaorkdn     766     ["live","jack","mark","spark","solid","maven","hold","poor","moon","apple"]     ["live","jack","-","-","-","-","hold","poor","moon","-"]
smjaphoplivecaorkdn     766     ["live","jack","mark","spark","solid","maven","moon","poor","hold","apple"]     ["live","jack","-","-","-","-","moon","poor","hold","-"]
sjmaphoplidveoarnck     768     ["solid","apple","poor","hold","moon","jack","maven","mark","spark","live"]     ["solid","-","-","-","moon","-","-","mark","-","-"]
smhjapoplivedcaorkn     768     ["live","solid","jack","maven","moon","hold","mark","spark","poor","apple"]     ["live","solid","-","-","-","-","-","-","poor","-"]
sjmaphoplivecoarknd     800     ["live","jack","maven","mark","poor","moon","spark","solid","hold","apple"]     ["live","jack","-","mark","-","moon","-","-","hold","-"]
hsmjapoplidvecoarkn     834     ["hold","apple","jack","maven","mark","solid","moon","poor","spark","live"]     ["hold","-","-","-","-","-","moon","poor","spark","-"]
shmjapoplidvecoarkn     834     ["solid","hold","apple","jack","maven","moon","mark","poor","spark","live"]     ["solid","-","apple","jack","-","-","-","poor","spark","-"]
hjmaspoplivedoarckn     836     ["live","hold","poor","jack","maven","moon","mark","apple","spark","solid"]     ["live","hold","-","-","-","-","-","-","-","-"]
sjmaphopliveoarcknd     848     ["live","poor","jack","maven","moon","mark","spark","solid","hold","apple"]     ["live","poor","-","-","-","-","-","-","hold","-"]
hmjaspopliveoncarkd     864     ["live","maven","moon","jack","hold","mark","poor","apple","spark","solid"]     ["live","-","-","-","-","-","-","apple","spark","-"]
sjmaphoplivedcoarkn     864     ["live","solid","jack","maven","mark","poor","hold","moon","spark","apple"]     ["live","solid","-","-","-","-","-","moon","-","-"]
hmjaspoplidvecaorkn     898     ["hold","apple","jack","maven","moon","mark","spark","poor","solid","live"]     ["hold","-","-","-","-","mark","-","poor","solid","-"]
shjmapoplivedcaorkn     904     ["live","solid","hold","jack","maven","mark","spark","poor","moon","apple"]     ["live","solid","-","jack","-","mark","-","poor","moon","-"]
hsmjapoplivecaorkdn     922     ["live","jack","hold","maven","mark","spark","apple","solid","moon","poor"]     ["live","jack","-","-","-","-","apple","-","-","-"]
shmjapoplivecaorkdn     922     ["live","jack","mark","spark","solid","maven","hold","moon","poor","apple"]     ["live","jack","-","-","-","-","hold","moon","poor","-"]
smhjapoplivecaorkdn     922     ["live","jack","mark","spark","solid","maven","moon","hold","poor","apple"]     ["live","jack","-","-","-","-","moon","hold","poor","-"]
hsjmapoplivecoarkdn     938     ["live","jack","hold","maven","mark","poor","moon","spark","apple","solid"]     ["live","jack","-","-","-","-","-","-","-","-"]
hsjmapoplivedoarckn     956     ["live","hold","poor","jack","maven","moon","mark","spark","apple","solid"]     ["live","hold","-","-","-","-","-","-","-","-"]
jmasppholiveonardck     960     ["apple","moon","poor","hold","jack","maven","mark","spark","solid","live"]     ["-","-","-","-","-","-","-","-","-","-"]
jmasppholiveoarndck     960     ["apple","poor","moon","hold","jack","maven","mark","spark","solid","live"]     ["-","-","-","-","-","-","-","-","-","-"]
shjmapoplidoarckven     960     ["solid","hold","poor","jack","maven","moon","mark","spark","apple","live"]     ["solid","hold","poor","-","-","-","-","-","-","-"]
shjmapoplidveoarckn     960     ["solid","hold","apple","poor","jack","maven","moon","mark","spark","live"]     ["solid","-","apple","-","-","-","-","mark","-","-"]
hmjaspopliveonardck     960     ["live","maven","moon","poor","hold","mark","jack","apple","spark","solid"]     ["live","-","-","-","-","-","-","-","-","-"]
hsjmapopliveoarckdn     972     ["live","poor","jack","hold","maven","moon","mark","spark","apple","solid"]     ["live","poor","-","-","-","-","-","-","-","-"]
hmjaspopliveoardnck     980     ["live","poor","hold","maven","moon","mark","jack","apple","spark","solid"]     ["live","poor","hold","-","-","-","-","-","-","-"]
hsmjapopliveoardckn     980     ["live","poor","hold","mark","maven","moon","jack","spark","apple","solid"]     ["live","poor","hold","-","-","-","-","-","-","-"]
sjmaphoplivecaorknd     992     ["live","jack","maven","mark","spark","poor","moon","solid","hold","apple"]     ["live","jack","-","-","-","-","-","-","hold","-"]
hjmaspoplivecoarkdn     1000    ["live","jack","hold","maven","mark","poor","moon","apple","spark","solid"]     ["live","jack","-","-","-","-","-","-","-","-"]
smhjapoplivecaorknd     1014    ["live","jack","maven","moon","mark","spark","solid","hold","poor","apple"]     ["live","jack","-","-","-","-","-","hold","poor","-"]
hsmjapoplivedoarnck     1020    ["live","hold","poor","maven","moon","mark","jack","spark","apple","solid"]     ["live","hold","-","-","-","-","-","-","-","-"]
jmspappholivecorknd     1024    ["live","jack","maven","moon","mark","spark","poor","apple","hold","solid"]     ["live","jack","-","-","-","-","-","-","hold","-"]
hsmjapopliveoarnckd     1030    ["live","poor","maven","moon","mark","hold","jack","spark","apple","solid"]     ["live","poor","-","-","mark","-","-","-","apple","-"]
hsjmapoplivecaorknd     1034    ["live","jack","maven","hold","mark","spark","poor","moon","apple","solid"]     ["live","jack","-","-","mark","-","-","-","apple","-"]
hsjmapoplivedaorckn     1040    ["live","hold","spark","jack","maven","mark","poor","moon","apple","solid"]     ["live","hold","-","-","-","-","-","-","-","-"]
shmjapoplivedoncark     1040    ["live","solid","maven","hold","moon","jack","mark","spark","poor","apple"]     ["live","solid","-","hold","moon","jack","-","spark","-","-"]
jmasppholiveoardnck     1056    ["apple","poor","hold","moon","jack","maven","mark","spark","solid","live"]     ["-","-","-","-","-","-","-","-","-","-"]
sjmaphoplivedcaorkn     1056    ["live","solid","jack","maven","mark","spark","poor","hold","moon","apple"]     ["live","solid","-","-","-","spark","-","-","-","-"]
smhjapopliveoncarkd     1104    ["live","maven","moon","jack","mark","spark","solid","hold","poor","apple"]     ["live","-","-","-","-","spark","-","hold","poor","-"]
hmsjapoplivedcaorkn     1118    ["live","hold","jack","maven","moon","mark","spark","poor","apple","solid"]     ["live","hold","-","-","-","mark","-","-","-","-"]
jmasppholivedoarnck     1120    ["apple","hold","poor","moon","jack","maven","mark","spark","solid","live"]     ["-","-","-","-","-","-","-","-","-","-"]
hsmjapoplivedcaorkn     1128    ["live","hold","jack","maven","mark","spark","apple","solid","moon","poor"]     ["live","hold","-","-","-","spark","-","-","-","-"]
shmjapoplivedcaorkn     1128    ["live","solid","hold","jack","maven","moon","mark","spark","poor","apple"]     ["live","solid","-","jack","-","-","-","-","poor","-"]
smjaphopliveondcark     1152    ["live","maven","moon","solid","jack","mark","spark","poor","hold","apple"]     ["live","-","-","-","jack","-","spark","-","hold","-"]
smjaphoplivedoncark     1152    ["live","solid","maven","moon","jack","mark","spark","poor","hold","apple"]     ["live","solid","-","moon","jack","-","spark","-","hold","-"]
hsmjapoplivedoncark     1160    ["live","hold","maven","jack","mark","spark","poor","moon","apple","solid"]     ["live","hold","-","-","-","-","poor","-","-","-"]
smhjapoplivedoncark     1168    ["live","solid","maven","moon","hold","jack","mark","spark","poor","apple"]     ["live","solid","-","moon","-","-","mark","-","poor","-"]
hsjmapoplidoarveckn     1184    ["hold","poor","solid","live","jack","maven","moon","mark","spark","apple"]     ["hold","-","-","live","-","-","-","mark","-","-"]
shmjapopliveondarck     1190    ["live","maven","solid","hold","moon","mark","jack","spark","poor","apple"]     ["live","maven","solid","-","-","-","-","-","poor","-"]
shmjapoplidveoarnck     1200    ["solid","hold","apple","poor","maven","moon","mark","jack","spark","live"]     ["solid","-","apple","-","-","moon","-","-","-","-"]
hmjaspopliveoarcknd     1218    ["live","mark","maven","hold","moon","jack","poor","apple","spark","solid"]     ["live","-","-","-","moon","-","-","apple","spark","-"]
hmjaspoplivedoarnck     1220    ["live","hold","poor","maven","moon","mark","jack","apple","spark","solid"]     ["live","hold","-","-","-","-","-","-","-","-"]
smjaphoplivecaorknd     1226    ["live","jack","maven","moon","mark","spark","poor","solid","hold","apple"]     ["live","jack","-","-","-","-","-","-","hold","-"]
smhjapopliveondcark     1238    ["live","maven","moon","solid","hold","jack","mark","spark","poor","apple"]     ["live","-","-","-","-","-","mark","-","poor","-"]
shjmapoplidveaorckn     1240    ["solid","hold","apple","spark","jack","maven","mark","poor","moon","live"]     ["solid","-","apple","spark","jack","-","-","poor","moon","-"]
smjaphoplidvecaorkn     1248    ["solid","apple","jack","maven","moon","mark","spark","poor","hold","live"]     ["solid","-","-","-","-","mark","-","poor","hold","-"]
jmasphooarplivednck     1256    ["poor","apple","hold","moon","jack","maven","mark","spark","solid","live"]     ["poor","-","-","-","-","-","-","-","-","-"]
hsmjapoplidovencark     1260    ["hold","solid","moon","maven","jack","mark","spark","poor","apple","live"]     ["hold","solid","moon","-","-","-","-","-","-","-"]
shmjapoplidovencark     1260    ["solid","hold","moon","maven","jack","mark","spark","poor","apple","live"]     ["solid","hold","moon","-","-","-","-","-","-","-"]
sjmaphoplidveaorckn     1280    ["solid","apple","spark","jack","maven","mark","poor","hold","moon","live"]     ["solid","-","-","-","-","-","-","-","-","-"]
spmjappholiveonrckd     1280    ["live","moon","spark","maven","mark","jack","poor","apple","hold","solid"]     ["live","moon","-","-","-","-","-","-","hold","-"]
smhjapoplidcoarkven     1344    ["solid","jack","maven","moon","hold","mark","poor","spark","apple","live"]     ["solid","jack","-","-","-","-","-","-","-","-"]
hmjaspopliveonarckd     1344    ["live","maven","moon","mark","hold","jack","poor","apple","spark","solid"]     ["live","-","-","-","-","-","-","apple","spark","-"]
sjmaphopliveoardckn     1344    ["live","poor","solid","hold","jack","maven","moon","mark","spark","apple"]     ["live","poor","solid","-","-","-","-","-","-","-"]
smjaphopliveoarnckd     1360    ["live","poor","maven","moon","mark","jack","spark","solid","hold","apple"]     ["live","poor","-","-","-","-","-","-","hold","-"]
sjmaphopliveaorckdn     1392    ["live","spark","jack","mark","poor","solid","maven","hold","moon","apple"]     ["live","spark","-","-","poor","-","-","-","-","-"]
sjmaphopliveoarckdn     1392    ["live","poor","jack","mark","spark","solid","maven","hold","moon","apple"]     ["live","poor","-","-","-","-","-","-","-","-"]
smjaphooarplivednck     1400    ["poor","live","hold","maven","moon","mark","jack","spark","apple","solid"]     ["poor","live","-","-","-","-","-","-","-","-"]
sjmaphooarplivedckn     1400    ["poor","live","hold","jack","maven","moon","mark","spark","apple","solid"]     ["poor","live","-","-","-","-","mark","-","-","-"]
shjmapoplidvecoarkn     1422    ["solid","hold","apple","jack","maven","mark","poor","moon","spark","live"]     ["solid","-","apple","jack","-","-","poor","-","-","-"]
smjaphopliveoarndck     1440    ["live","poor","maven","moon","solid","hold","mark","jack","spark","apple"]     ["live","poor","-","-","-","-","mark","jack","-","-"]
hsjmapoplidoarvenck     1456    ["hold","poor","moon","jack","maven","mark","spark","apple","solid","live"]     ["hold","-","-","-","-","-","spark","-","-","-"]
hmsjapoplivedoncark     1468    ["live","hold","maven","moon","jack","mark","spark","poor","apple","solid"]     ["live","hold","-","moon","-","-","-","-","-","-"]
hmsjapoplivecaorkdn     1474    ["live","jack","hold","maven","moon","mark","spark","poor","apple","solid"]     ["live","jack","-","-","-","-","-","-","-","-"]
hjmaspoplidvecaorkn     1496    ["hold","apple","jack","maven","mark","spark","poor","moon","solid","live"]     ["hold","-","-","-","-","-","-","-","-","-"]
hjmaspoplidvecoarkn     1504    ["hold","apple","jack","maven","mark","poor","moon","spark","solid","live"]     ["hold","-","-","-","-","-","-","spark","-","-"]
hsjmapoplivedcaorkn     1520    ["live","hold","jack","maven","mark","spark","poor","moon","apple","solid"]     ["live","hold","-","-","-","-","-","-","-","-"]
shmjapoplivedoarckn     1520    ["live","solid","hold","mark","maven","moon","jack","poor","spark","apple"]     ["live","solid","-","mark","-","-","-","-","-","-"]
smhjapoplidvecaorkn     1536    ["solid","apple","jack","maven","moon","hold","mark","spark","poor","live"]     ["solid","-","-","-","-","-","-","-","poor","-"]
sjmaphoplivedoarckn     1536    ["live","solid","poor","hold","jack","maven","moon","mark","spark","apple"]     ["live","solid","-","-","-","-","-","-","-","-"]
hmjaspoplidcaorkven     1568    ["hold","jack","maven","moon","mark","apple","spark","poor","solid","live"]     ["hold","jack","-","-","-","-","-","poor","solid","-"]
hjmaspoplidoarvenck     1568    ["hold","poor","moon","jack","maven","mark","apple","spark","solid","live"]     ["hold","poor","-","-","-","-","-","-","-","-"]
sjmaphoplivecoarkdn     1584    ["live","jack","mark","poor","spark","solid","maven","hold","moon","apple"]     ["live","jack","-","-","-","-","-","-","-","-"]
hmsjapopliveondcark     1598    ["live","maven","hold","moon","jack","mark","spark","poor","apple","solid"]     ["live","-","hold","-","-","-","-","-","-","-"]
hsmjapoplidoarveckn     1600    ["hold","poor","solid","live","mark","maven","moon","jack","spark","apple"]     ["hold","-","-","live","-","-","-","jack","-","-"]
sjmaphooarplidveckn     1600    ["poor","hold","solid","live","jack","maven","moon","mark","spark","apple"]     ["poor","-","-","-","-","-","-","-","-","-"]
hsjmapoplidvecoarkn     1646    ["hold","apple","jack","maven","mark","solid","poor","moon","spark","live"]     ["hold","-","-","-","-","-","-","-","-","-"]
hsjmapoplidveoarckn     1660    ["hold","apple","solid","poor","jack","maven","moon","mark","spark","live"]     ["hold","-","solid","-","-","-","-","mark","-","-"]
jspmappholivecorknd     1664    ["live","jack","moon","spark","maven","mark","poor","apple","hold","solid"]     ["live","jack","-","spark","-","mark","-","-","hold","-"]
hmjaspoplidaorckven     1680    ["hold","mark","maven","moon","jack","apple","spark","poor","solid","live"]     ["hold","mark","-","-","-","-","-","-","-","-"]
shmjapoplidoarvenck     1680    ["solid","hold","poor","maven","moon","mark","jack","spark","apple","live"]     ["solid","hold","poor","-","-","-","-","-","-","-"]
smhjapoplidoarckven     1680    ["solid","mark","maven","moon","hold","jack","poor","spark","apple","live"]     ["solid","mark","-","-","-","-","-","-","-","-"]
smjaphopliveoardnck     1680    ["live","poor","solid","maven","hold","moon","mark","jack","spark","apple"]     ["live","poor","solid","-","-","-","mark","jack","-","-"]
smjaphopliveoardckn     1680    ["live","poor","solid","hold","mark","maven","moon","jack","spark","apple"]     ["live","poor","solid","-","-","-","-","-","-","-"]
smhjapoplivedaorckn     1680    ["live","solid","mark","maven","moon","hold","jack","spark","poor","apple"]     ["live","solid","-","-","-","-","-","-","poor","-"]
sjmaphoplidvecoarkn     1728    ["solid","apple","jack","maven","mark","poor","hold","moon","spark","live"]     ["solid","-","-","-","-","-","-","moon","-","-"]
hmjaspoplidcoarkven     1792    ["hold","jack","maven","moon","mark","poor","apple","spark","solid","live"]     ["hold","jack","-","-","mark","-","-","-","-","-"]
hsjmapoplidveaorckn     1800    ["hold","apple","spark","jack","maven","mark","solid","poor","moon","live"]     ["hold","-","-","-","-","-","-","-","moon","-"]
hsjmapopliveaorckdn     1812    ["live","spark","hold","jack","maven","mark","poor","moon","apple","solid"]     ["live","spark","-","jack","-","-","-","-","-","-"]
hmsjapoplidvecaorkn     1886    ["hold","apple","jack","maven","moon","mark","spark","solid","poor","live"]     ["hold","-","-","-","-","mark","-","solid","poor","-"]
hsmjapoplidveoarnck     1900    ["hold","apple","solid","poor","maven","moon","mark","jack","spark","live"]     ["hold","-","solid","-","-","moon","-","-","-","-"]
hsmjapopliveoarcknd     1902    ["live","mark","maven","hold","jack","poor","moon","spark","apple","solid"]     ["live","-","-","-","jack","-","-","-","apple","-"]
hmsjapoplidcoarkven     1904    ["hold","jack","maven","moon","mark","poor","spark","apple","solid","live"]     ["hold","jack","-","-","mark","-","-","-","-","-"]
spjmappholiveorckdn     1908    ["live","spark","jack","mark","poor","apple","hold","maven","moon","solid"]     ["live","-","-","-","-","-","-","-","-","-"]
hsmjapopliveondarck     1910    ["live","maven","hold","mark","jack","spark","poor","moon","apple","solid"]     ["live","maven","hold","-","-","-","-","-","-","-"]
smjaphopliveonardck     1920    ["live","maven","moon","poor","solid","hold","mark","jack","spark","apple"]     ["live","-","-","-","-","-","-","-","-","-"]
smjaphoplivedoarnck     1920    ["live","solid","poor","maven","hold","moon","mark","jack","spark","apple"]     ["live","solid","-","-","-","-","mark","jack","-","-"]
smjaphooarplivedckn     1960    ["poor","live","hold","mark","maven","moon","jack","spark","apple","solid"]     ["poor","live","-","-","-","-","jack","-","-","-"]
sjmaphooarplivecknd     1960    ["poor","live","jack","maven","hold","moon","mark","spark","apple","solid"]     ["poor","live","-","-","-","-","-","-","-","-"]
hsmjapoplidcoarkven     1974    ["hold","jack","maven","mark","apple","solid","moon","poor","spark","live"]     ["hold","-","-","-","apple","-","moon","poor","spark","-"]
shmjapoplidcoarkven     1974    ["solid","hold","jack","maven","moon","mark","poor","spark","apple","live"]     ["solid","-","-","-","-","-","-","-","-","-"]
smhjapopliveaorckdn     2000    ["live","mark","jack","spark","solid","maven","moon","hold","poor","apple"]     ["live","-","-","-","-","-","moon","hold","poor","-"]
sjmaphoplivecaorkdn     2000    ["live","jack","mark","spark","poor","solid","maven","hold","moon","apple"]     ["live","jack","-","-","poor","-","-","-","-","-"]
hmsjapoplivecaorknd     2062    ["live","jack","maven","hold","moon","mark","spark","poor","apple","solid"]     ["live","jack","-","-","moon","-","-","-","apple","-"]
jmasppholiveoarnckd     2100    ["apple","poor","moon","jack","maven","hold","mark","spark","solid","live"]     ["-","-","-","-","-","-","-","-","-","-"]
hmjaspopliveoarckdn     2100    ["live","mark","hold","maven","moon","jack","poor","apple","spark","solid"]     ["live","-","-","-","-","-","-","-","-","-"]
jmasppholiveondarck     2112    ["apple","moon","hold","spark","jack","maven","mark","poor","solid","live"]     ["-","-","-","-","-","-","-","-","-","-"]
sjmaphoplidvecaorkn     2112    ["solid","apple","jack","maven","mark","spark","poor","hold","moon","live"]     ["solid","-","-","-","-","spark","-","-","-","-"]
sjmaphooarplivendck     2160    ["poor","moon","hold","jack","maven","mark","spark","apple","solid","live"]     ["poor","-","-","-","-","-","-","-","-","-"]
smhjapopliveaorcknd     2200    ["live","mark","maven","moon","jack","spark","solid","hold","poor","apple"]     ["live","-","-","-","-","-","-","hold","poor","-"]
hmjaspopliveondarck     2208    ["live","maven","hold","moon","mark","jack","poor","apple","spark","solid"]     ["live","-","hold","-","-","-","-","-","-","-"]
smhjapopliveonarckd     2208    ["live","maven","moon","mark","jack","spark","solid","hold","poor","apple"]     ["live","-","-","-","-","-","-","hold","poor","-"]
hmsjapopliveoncarkd     2213    ["live","maven","moon","jack","hold","mark","spark","poor","apple","solid"]     ["live","-","-","-","-","mark","-","-","apple","-"]
hmjaspoplivedoarckn     2230    ["live","hold","mark","maven","moon","jack","poor","apple","spark","solid"]     ["live","hold","-","-","-","-","-","-","-","-"]
sjmaphooarplidvenck     2240    ["poor","hold","moon","jack","maven","mark","spark","apple","solid","live"]     ["poor","-","-","-","-","-","-","-","-","-"]
smjaphooarplidveckn     2240    ["poor","hold","solid","live","mark","maven","moon","jack","spark","apple"]     ["poor","-","-","-","-","-","-","-","-","-"]
sjmaphooarpliveckdn     2240    ["poor","live","jack","hold","maven","moon","mark","spark","apple","solid"]     ["poor","live","-","-","-","-","mark","-","-","-"]
jmasppholivedonarck     2240    ["apple","hold","moon","spark","jack","maven","mark","poor","solid","live"]     ["-","-","-","-","-","-","-","-","-","-"]
hjmaspoplidoarveckn     2272    ["hold","poor","apple","jack","maven","moon","mark","spark","solid","live"]     ["hold","poor","-","-","-","-","-","-","-","-"]
shjmapoplidvecaorkn     2298    ["solid","hold","apple","jack","maven","mark","spark","poor","moon","live"]     ["solid","-","apple","jack","-","mark","-","poor","moon","-"]
hsjmapoplivecaorkdn     2326    ["live","jack","hold","maven","mark","spark","poor","moon","apple","solid"]     ["live","jack","-","-","mark","-","-","-","-","-"]
hmjaspoplidovencark     2352    ["hold","moon","maven","jack","mark","poor","apple","spark","solid","live"]     ["hold","moon","-","-","-","poor","-","spark","-","-"]
smjaphoplidcoarkven     2352    ["solid","jack","maven","moon","mark","poor","hold","spark","apple","live"]     ["solid","jack","-","-","mark","-","-","spark","-","-"]
hjmaspoplidveoarckn     2372    ["hold","apple","poor","jack","maven","moon","mark","spark","solid","live"]     ["hold","-","-","-","-","-","-","-","-","-"]
mspjappholiveorcknd     2376    ["live","mark","maven","moon","spark","jack","poor","apple","hold","solid"]     ["live","-","-","-","-","jack","-","-","hold","-"]
smjaphopliveoncarkd     2400    ["live","maven","moon","jack","mark","spark","poor","solid","hold","apple"]     ["live","-","-","-","-","-","-","-","hold","-"]
hsmjapopliveonarckd     2401    ["live","maven","mark","hold","jack","spark","poor","moon","apple","solid"]     ["live","maven","-","-","jack","-","-","-","-","-"]
hjmaspoplidcaorkven     2464    ["hold","jack","maven","mark","apple","spark","poor","moon","solid","live"]     ["hold","jack","-","-","-","-","-","-","-","-"]
hmjaspoplivedonarck     2508    ["live","hold","maven","moon","mark","jack","poor","apple","spark","solid"]     ["live","hold","-","moon","-","-","-","-","-","-"]
hsmjapopliveaorcknd     2588    ["live","mark","maven","hold","jack","spark","poor","moon","apple","solid"]     ["live","-","-","-","jack","-","-","-","apple","-"]
spmjappholiveorckdn     2628    ["live","spark","mark","jack","poor","apple","hold","maven","moon","solid"]     ["live","-","-","-","-","-","-","-","-","-"]
smhjapoplivedonarck     2672    ["live","solid","maven","moon","hold","mark","jack","spark","poor","apple"]     ["live","solid","-","moon","-","-","-","-","poor","-"]
hmsjapoplidoarckven     2688    ["hold","mark","maven","moon","jack","poor","spark","apple","solid","live"]     ["hold","mark","-","-","jack","-","-","-","-","-"]
sjmaphoplidoarvenck     2688    ["solid","poor","hold","moon","jack","maven","mark","spark","apple","live"]     ["solid","poor","-","-","-","-","-","-","-","-"]
hmjaspoplidoarveckn     2720    ["hold","poor","apple","mark","maven","moon","jack","spark","solid","live"]     ["hold","poor","-","-","-","-","-","-","-","-"]
smjaphooarpliveckdn     2800    ["poor","live","mark","hold","maven","moon","jack","spark","apple","solid"]     ["poor","live","-","-","-","-","jack","-","-","-"]
shmjapoplivedonarck     2800    ["live","solid","maven","hold","moon","mark","jack","spark","poor","apple"]     ["live","solid","-","hold","moon","-","-","-","-","-"]
hmsjapoplivedaorckn     2814    ["live","hold","mark","maven","moon","jack","spark","poor","apple","solid"]     ["live","hold","-","-","-","-","-","-","-","-"]
smhjapopliveondarck     2842    ["live","maven","moon","solid","hold","mark","jack","spark","poor","apple"]     ["live","-","-","-","-","-","-","-","poor","-"]
hjmaspoplidoarckven     2880    ["hold","poor","jack","maven","moon","mark","apple","spark","solid","live"]     ["hold","poor","-","-","-","-","-","-","-","-"]
hsmjapoplidvecaorkn     2886    ["hold","apple","jack","maven","mark","spark","solid","moon","poor","live"]     ["hold","-","-","-","-","spark","-","moon","poor","-"]
shmjapoplidvecaorkn     2886    ["solid","hold","apple","jack","maven","moon","mark","spark","poor","live"]     ["solid","-","apple","jack","-","-","-","-","poor","-"]
hsjmapoplidvecaorkn     2914    ["hold","apple","jack","maven","mark","spark","solid","poor","moon","live"]     ["hold","-","-","-","-","-","-","-","moon","-"]
hsmjapoplivedoarckn     3004    ["live","hold","mark","maven","jack","poor","moon","spark","apple","solid"]     ["live","hold","-","-","-","-","-","-","-","-"]
sjmaphoplidoarveckn     3072    ["solid","poor","hold","apple","jack","maven","moon","mark","spark","live"]     ["solid","poor","-","apple","-","-","-","-","-","-"]
sjmaphoplidveoarckn     3072    ["solid","apple","poor","hold","jack","maven","moon","mark","spark","live"]     ["solid","-","-","-","-","-","-","-","-","-"]
smjaphooarplivecknd     3080    ["poor","live","mark","maven","hold","moon","jack","spark","apple","solid"]     ["poor","live","-","-","-","-","-","-","-","-"]
shjmapoplidaorckven     3080    ["solid","hold","spark","jack","maven","mark","poor","moon","apple","live"]     ["solid","-","-","-","-","mark","-","-","-","-"]
spjmappholiveorcknd     3132    ["live","spark","moon","jack","maven","mark","poor","apple","hold","solid"]     ["live","-","-","-","-","mark","-","-","hold","-"]
jmasphooarplidvenck     3136    ["poor","hold","moon","jack","maven","mark","apple","spark","solid","live"]     ["poor","-","-","-","-","-","-","-","-","-"]
hmjaspoplidveoarnck     3140    ["hold","apple","poor","maven","moon","mark","jack","spark","solid","live"]     ["hold","-","-","-","-","-","-","-","-","-"]
jmasppholiveondcark     3168    ["apple","moon","hold","jack","maven","mark","spark","poor","solid","live"]     ["-","-","-","-","-","-","spark","-","-","-"]
hsmjapopliveoarckdn     3180    ["live","mark","hold","maven","jack","poor","moon","spark","apple","solid"]     ["live","-","-","-","jack","-","-","-","-","-"]
smjaphoplivedaorckn     3200    ["live","solid","mark","maven","moon","jack","spark","poor","hold","apple"]     ["live","solid","-","-","-","-","-","-","hold","-"]
shmjapopliveaorckdn     3340    ["live","mark","jack","spark","solid","maven","hold","moon","poor","apple"]     ["live","-","-","-","-","-","hold","moon","poor","-"]
jmasppholivedoncark     3360    ["apple","hold","moon","jack","maven","mark","spark","poor","solid","live"]     ["-","-","-","-","-","-","spark","-","-","-"]
smhjapoplidveaorckn     3360    ["solid","apple","mark","maven","moon","hold","jack","spark","poor","live"]     ["solid","-","-","-","-","-","-","-","poor","-"]
shjmapoplidcoarkven     3402    ["solid","hold","jack","maven","mark","poor","moon","spark","apple","live"]     ["solid","-","-","-","mark","-","-","spark","-","-"]
mjspappholiveonrdck     3456    ["maven","moon","poor","apple","hold","mark","jack","spark","solid","live"]     ["maven","-","-","-","-","-","-","-","-","-"]
mspjappholiveonrdck     3456    ["maven","moon","poor","apple","hold","mark","spark","jack","solid","live"]     ["maven","-","-","-","-","-","-","-","-","-"]
smjaphopliveoarcknd     3472    ["live","mark","maven","moon","jack","poor","spark","solid","hold","apple"]     ["live","-","-","-","jack","-","-","-","hold","-"]
hsmjapoplivedonarck     3520    ["live","hold","maven","mark","jack","spark","poor","moon","apple","solid"]     ["live","hold","-","-","-","-","-","-","-","-"]
jmasphooarplivendck     3600    ["poor","moon","hold","jack","maven","mark","apple","spark","solid","live"]     ["poor","-","-","-","-","-","-","-","-","-"]
hmsjapopliveaorckdn     3616    ["live","mark","hold","maven","moon","jack","spark","poor","apple","solid"]     ["live","-","-","-","-","-","-","-","-","-"]
hsmjapoplidovenarck     3780    ["hold","solid","moon","maven","mark","jack","spark","poor","apple","live"]     ["hold","solid","moon","-","-","-","spark","-","-","-"]
shmjapoplidovenarck     3780    ["solid","hold","moon","maven","mark","jack","spark","poor","apple","live"]     ["solid","hold","moon","-","-","-","spark","-","-","-"]
hmjaspoplidveaorckn     3810    ["hold","apple","mark","maven","moon","jack","spark","poor","solid","live"]     ["hold","-","-","-","-","-","-","-","-","-"]
smjaphoplidoarveckn     3840    ["solid","poor","hold","apple","mark","maven","moon","jack","spark","live"]     ["solid","poor","-","apple","-","-","-","-","-","-"]
smjaphoplidveoarnck     3840    ["solid","apple","poor","maven","hold","moon","mark","jack","spark","live"]     ["solid","-","-","-","-","-","mark","jack","-","-"]
smjaphoplivedoarckn     3840    ["live","solid","mark","maven","moon","jack","poor","hold","spark","apple"]     ["live","solid","-","-","-","-","-","-","-","-"]
mhjaspooplivendcark     3888    ["moon","maven","hold","jack","mark","poor","apple","spark","solid","live"]     ["moon","-","-","-","-","poor","-","spark","-","-"]
smjaphoplidovencark     4032    ["solid","moon","maven","jack","mark","spark","poor","hold","apple","live"]     ["solid","moon","-","-","-","-","-","-","-","-"]
hmsjapoplivedonarck     4052    ["live","hold","maven","moon","mark","jack","spark","poor","apple","solid"]     ["live","hold","-","moon","-","-","spark","-","-","-"]
shmjapoplivedaorckn     4080    ["live","solid","hold","mark","maven","moon","jack","spark","poor","apple"]     ["live","solid","-","-","-","-","-","-","poor","-"]
jmasppholiveoardckn     4224    ["apple","poor","hold","jack","maven","moon","mark","spark","solid","live"]     ["-","-","-","-","-","-","mark","-","-","-"]
hmjaspoplidveoncark     4236    ["hold","maven","moon","jack","mark","poor","apple","spark","solid","live"]     ["hold","-","-","-","-","poor","-","spark","-","-"]
hjmaspoplidcoarkven     4256    ["hold","jack","maven","mark","poor","moon","apple","spark","solid","live"]     ["hold","jack","-","-","poor","-","-","spark","-","-"]
mjspappholiveondrck     4320    ["maven","moon","apple","hold","mark","jack","spark","poor","solid","live"]     ["maven","-","apple","-","-","jack","spark","-","-","-"]
mjspappholiveondcrk     4320    ["maven","moon","apple","hold","jack","mark","spark","poor","solid","live"]     ["maven","-","apple","-","jack","-","spark","-","-","-"]
mjasphooarckplivedn     4320    ["poor","mark","jack","apple","hold","maven","moon","spark","solid","live"]     ["poor","mark","-","-","-","-","-","-","-","-"]
jmasphooarckplivedn     4320    ["poor","jack","mark","apple","hold","maven","moon","spark","solid","live"]     ["poor","jack","-","-","-","-","-","-","-","-"]
smjaphoplidcaorkven     4368    ["solid","jack","maven","moon","mark","spark","poor","hold","apple","live"]     ["solid","jack","-","-","-","-","-","-","-","-"]
shmjapoplidveoarckn     4440    ["solid","hold","apple","mark","maven","moon","jack","poor","spark","live"]     ["solid","-","apple","mark","-","-","-","-","-","-"]
smhjapoplidveoncark     4464    ["solid","maven","moon","hold","jack","mark","spark","poor","apple","live"]     ["solid","-","-","-","jack","-","-","-","-","-"]
jmasppholivedoarckn     4480    ["apple","hold","poor","jack","maven","moon","mark","spark","solid","live"]     ["-","-","-","-","-","-","mark","-","-","-"]
sjmaphoplidaorckven     4480    ["solid","spark","jack","maven","mark","poor","hold","moon","apple","live"]     ["solid","spark","-","-","-","-","-","moon","-","-"]
hmsjapoplidveaorckn     4494    ["hold","apple","mark","maven","moon","jack","spark","solid","poor","live"]     ["hold","-","-","-","-","-","-","solid","poor","-"]
hmsjapopliveondarck     4522    ["live","maven","hold","moon","mark","jack","spark","poor","apple","solid"]     ["live","-","hold","-","-","-","spark","-","-","-"]
jmasphooarplidveckn     4544    ["poor","hold","apple","jack","maven","moon","mark","spark","solid","live"]     ["poor","-","-","-","-","-","mark","-","-","-"]
smjaphopliveondarck     4608    ["live","maven","moon","solid","mark","jack","spark","poor","hold","apple"]     ["live","-","-","-","-","-","-","-","hold","-"]
smjaphoplivedonarck     4608    ["live","solid","maven","moon","mark","jack","spark","poor","hold","apple"]     ["live","solid","-","moon","-","-","-","-","hold","-"]
smjaphopliveaorcknd     4688    ["live","mark","maven","moon","jack","spark","poor","solid","hold","apple"]     ["live","-","-","-","jack","-","-","-","hold","-"]
smjaphopliveoarckdn     4704    ["live","mark","jack","poor","spark","solid","maven","hold","moon","apple"]     ["live","-","-","-","-","-","-","-","-","-"]
jmasppholiveonarckd     4740    ["apple","moon","spark","hold","jack","maven","mark","poor","solid","live"]     ["-","-","-","-","-","-","-","-","-","-"]
jmasphooarplivedckn     4744    ["poor","apple","hold","jack","maven","moon","mark","spark","solid","live"]     ["poor","-","-","-","-","-","mark","-","-","-"]
smjaphopliveaorckdn     4944    ["live","mark","jack","spark","poor","solid","maven","hold","moon","apple"]     ["live","-","-","-","poor","-","-","-","-","-"]
hmsjapopliveaorcknd     4952    ["live","mark","maven","hold","moon","jack","spark","poor","apple","solid"]     ["live","-","-","-","moon","-","-","-","apple","-"]
mjasppholivedoncark     5040    ["apple","hold","maven","moon","jack","mark","spark","poor","solid","live"]     ["-","-","-","moon","-","-","-","poor","-","-"]
hsjmapoplidcoarkven     5194    ["hold","jack","maven","mark","poor","moon","spark","apple","solid","live"]     ["hold","-","-","-","-","-","-","-","-","-"]
sjmaphooarckplivedn     5200    ["poor","jack","mark","spark","apple","hold","maven","moon","solid","live"]     ["poor","-","-","-","apple","-","-","moon","-","-"]
mjasppholiveoardnck     5280    ["apple","poor","hold","maven","moon","mark","jack","spark","solid","live"]     ["-","-","-","-","moon","-","-","-","-","-"]
mjasppholiveoardckn     5280    ["apple","poor","hold","mark","maven","moon","jack","spark","solid","live"]     ["-","-","-","-","-","-","jack","-","-","-"]
smhjapoplidcaorkven     5376    ["solid","jack","maven","moon","hold","mark","spark","poor","apple","live"]     ["solid","jack","-","-","-","mark","-","-","-","-"]
sjmaphooarplivenckd     5400    ["poor","moon","jack","maven","hold","mark","spark","apple","solid","live"]     ["poor","-","-","-","-","-","-","-","-","-"]
jmasphooarplivecknd     5400    ["poor","apple","jack","maven","hold","moon","mark","spark","solid","live"]     ["poor","-","-","-","-","-","-","-","-","-"]
mjasphooarplidveckn     5440    ["poor","hold","apple","mark","maven","moon","jack","spark","solid","live"]     ["poor","-","-","-","-","-","jack","-","-","-"]
hmsjapoplidveoncark     5484    ["hold","maven","moon","jack","mark","spark","poor","apple","solid","live"]     ["hold","-","-","-","-","-","poor","-","-","-"]
hsmjapoplivedaorckn     5536    ["live","hold","mark","maven","jack","spark","poor","moon","apple","solid"]     ["live","hold","-","-","-","-","-","-","-","-"]
jmasppholivedcoarkn     5600    ["apple","hold","jack","maven","moon","mark","poor","spark","solid","live"]     ["-","-","-","-","-","mark","-","-","-","-"]
jmasppholivedaorckn     5600    ["apple","hold","spark","moon","jack","maven","mark","poor","solid","live"]     ["-","-","-","-","-","-","mark","-","-","-"]
mjasppholivedoarnck     5600    ["apple","hold","poor","maven","moon","mark","jack","spark","solid","live"]     ["-","-","-","-","moon","-","-","-","-","-"]
mjasphooarplivedckn     5720    ["poor","apple","hold","mark","maven","moon","jack","spark","solid","live"]     ["poor","-","-","-","-","-","jack","-","-","-"]
hsjmapoplidoarckven     5760    ["hold","poor","jack","maven","moon","mark","spark","apple","solid","live"]     ["hold","-","-","-","-","-","-","-","-","-"]
mhjaspooplivencarkd     5760    ["moon","maven","jack","hold","mark","poor","apple","spark","solid","live"]     ["moon","-","-","-","-","-","-","-","solid","-"]
mjasphooarplidckven     5760    ["poor","hold","mark","maven","moon","jack","apple","spark","solid","live"]     ["poor","-","mark","-","-","-","-","-","-","-"]
jmasphooarplidckven     5760    ["poor","hold","jack","maven","moon","mark","apple","spark","solid","live"]     ["poor","-","jack","-","-","-","-","-","-","-"]
mjasphooarckplidven     5760    ["poor","mark","hold","maven","moon","jack","apple","spark","solid","live"]     ["poor","mark","-","-","-","-","-","-","-","-"]
jmasphooarckplidven     5760    ["poor","jack","hold","maven","moon","mark","apple","spark","solid","live"]     ["poor","jack","-","-","-","-","-","-","-","-"]
jmasphooarpliveckdn     5760    ["poor","apple","jack","hold","maven","moon","mark","spark","solid","live"]     ["poor","-","-","-","-","-","mark","-","-","-"]
shjmapoplidcaorkven     5838    ["solid","hold","jack","maven","mark","spark","poor","moon","apple","live"]     ["solid","-","-","-","-","-","-","-","-","-"]
hmsjapopliveonarckd     5855    ["live","maven","moon","mark","hold","jack","spark","poor","apple","solid"]     ["live","-","-","-","-","-","-","-","apple","-"]
jmasppholiveoarcknd     5900    ["apple","poor","jack","maven","hold","moon","mark","spark","solid","live"]     ["-","-","-","-","-","-","-","-","-","-"]
jmasppholiveoarckdn     5920    ["apple","poor","jack","hold","maven","moon","mark","spark","solid","live"]     ["-","-","-","-","-","-","mark","-","-","-"]
hsmjapoplidveoarckn     5924    ["hold","apple","mark","maven","jack","solid","moon","poor","spark","live"]     ["hold","-","-","-","-","-","-","-","-","-"]
msjaphooplivendcark     6048    ["moon","maven","apple","solid","jack","mark","spark","poor","hold","live"]     ["moon","-","-","-","jack","-","spark","-","hold","-"]
mjasppholiveoarndck     6048    ["apple","poor","maven","hold","moon","mark","jack","spark","solid","live"]     ["-","-","-","-","-","-","-","-","-","-"]
smhjapoplidovencark     6048    ["solid","moon","maven","hold","jack","mark","spark","poor","apple","live"]     ["solid","moon","-","-","jack","-","-","-","-","-"]
sjmaphoplidcoarkven     6048    ["solid","jack","maven","mark","poor","hold","moon","spark","apple","live"]     ["solid","jack","-","-","poor","-","-","-","-","-"]
hmjaspoplidveoarckn     6070    ["hold","apple","mark","maven","moon","jack","poor","spark","solid","live"]     ["hold","-","-","-","-","-","-","-","-","-"]
jmasphooarplivenckd     6120    ["poor","moon","jack","maven","hold","mark","apple","spark","solid","live"]     ["poor","-","-","-","-","-","-","-","-","-"]
mjasppholiveondcark     6192    ["apple","maven","hold","moon","jack","mark","spark","poor","solid","live"]     ["-","-","-","-","-","-","-","poor","-","-"]
mjasphooarplivednck     6280    ["poor","apple","hold","maven","moon","mark","jack","spark","solid","live"]     ["poor","-","-","-","moon","-","-","-","-","-"]
smjaphooarckplivedn     6320    ["poor","mark","jack","spark","apple","hold","maven","moon","solid","live"]     ["poor","-","-","-","apple","-","-","moon","-","-"]
smjaphoplidveoncark     6336    ["solid","maven","moon","jack","mark","spark","poor","hold","apple","live"]     ["solid","-","-","-","-","-","-","-","-","-"]
smjaphoplidveaorckn     6400    ["solid","apple","mark","maven","moon","jack","spark","poor","hold","live"]     ["solid","-","-","-","-","-","-","-","hold","-"]
hsmjapopliveaorckdn     6428    ["live","mark","hold","maven","jack","spark","poor","moon","apple","solid"]     ["live","-","-","-","jack","-","-","-","-","-"]
mjasphooarpliveckdn     6480    ["poor","apple","mark","hold","maven","moon","jack","spark","solid","live"]     ["poor","-","-","-","-","-","jack","-","-","-"]
smjaphopliveonarckd     6720    ["live","maven","moon","mark","jack","spark","poor","solid","hold","apple"]     ["live","-","-","-","-","-","-","-","hold","-"]
mjasphooarplivecknd     6840    ["poor","apple","mark","maven","hold","moon","jack","spark","solid","live"]     ["poor","-","-","-","-","-","-","-","-","-"]
jmasppholiveaorcknd     7000    ["apple","spark","moon","hold","jack","maven","mark","poor","solid","live"]     ["-","-","-","-","jack","-","-","-","-","-"]
mhjaspooplivenarckd     7200    ["moon","maven","mark","hold","jack","poor","apple","spark","solid","live"]     ["moon","-","-","-","jack","-","-","-","solid","-"]
hsmjapoplidcaorkven     7266    ["hold","jack","maven","mark","spark","apple","solid","moon","poor","live"]     ["hold","-","-","-","-","-","-","moon","poor","-"]
shmjapoplidcaorkven     7266    ["solid","hold","jack","maven","moon","mark","spark","poor","apple","live"]     ["solid","-","-","-","-","mark","-","-","-","-"]
hsmjapoplidoarvenck     7280    ["hold","poor","maven","moon","mark","jack","spark","apple","solid","live"]     ["hold","-","-","-","-","-","spark","-","-","-"]
mjasppholiveonardck     7296    ["apple","maven","moon","poor","hold","mark","jack","spark","solid","live"]     ["-","-","moon","poor","-","-","-","-","-","-"]
sjmaphoplidcaorkven     7392    ["solid","jack","maven","mark","spark","poor","hold","moon","apple","live"]     ["solid","jack","-","-","-","-","-","moon","-","-"]
spmjappholiveorcknd     7452    ["live","spark","maven","moon","mark","jack","poor","apple","hold","solid"]     ["live","-","-","-","mark","jack","-","-","hold","-"]
hsjmapoplidaorckven     7560    ["hold","spark","jack","maven","mark","poor","moon","apple","solid","live"]     ["hold","-","-","-","-","poor","-","-","-","-"]
sjmaphoplidoarckven     7680    ["solid","poor","hold","jack","maven","moon","mark","spark","apple","live"]     ["solid","poor","-","-","-","-","mark","-","-","-"]
smjaphoplidveoarckn     7680    ["solid","apple","mark","maven","moon","jack","poor","hold","spark","live"]     ["solid","-","-","-","-","-","-","-","-","-"]
hmjaspoplidovenarck     7728    ["hold","moon","maven","mark","jack","poor","apple","spark","solid","live"]     ["hold","moon","-","-","-","-","-","-","-","-"]
hmsjapoplidovencark     7728    ["hold","moon","maven","jack","mark","spark","poor","apple","solid","live"]     ["hold","moon","-","-","-","-","poor","-","-","-"]
hmjaspoplidoarvenck     7840    ["hold","poor","maven","moon","mark","jack","apple","spark","solid","live"]     ["hold","poor","-","-","-","-","-","-","-","-"]
shmjapoplidveoncark     8100    ["solid","maven","hold","moon","jack","mark","spark","poor","apple","live"]     ["solid","-","-","-","-","-","-","-","-","-"]
hmsjapoplidcaorkven     8176    ["hold","jack","maven","moon","mark","spark","poor","apple","solid","live"]     ["hold","jack","-","-","-","-","-","-","-","-"]
mjspahoppliveonrdck     8640    ["maven","moon","poor","hold","mark","jack","spark","apple","solid","live"]     ["maven","-","poor","-","-","jack","spark","-","-","-"]
mspjahoppliveonrdck     8640    ["maven","moon","poor","hold","mark","spark","jack","apple","solid","live"]     ["maven","-","poor","-","-","spark","jack","-","-","-"]
mspjappholiveondrck     8640    ["maven","moon","apple","hold","mark","spark","jack","poor","solid","live"]     ["maven","-","apple","-","-","spark","jack","-","-","-"]
msjaphooplivenardck     8640    ["moon","maven","poor","hold","mark","jack","spark","apple","solid","live"]     ["moon","-","poor","-","-","-","-","-","-","-"]
shmjapoplidoarckven     8760    ["solid","hold","mark","maven","moon","jack","poor","spark","apple","live"]     ["solid","-","-","-","-","-","poor","spark","-","-"]
mshjapooplivendcark     9072    ["moon","maven","apple","solid","hold","jack","mark","spark","poor","live"]     ["moon","-","-","-","-","-","mark","-","poor","-"]
hsmjapoplidveoncark     9180    ["hold","maven","jack","mark","spark","poor","moon","apple","solid","live"]     ["hold","-","-","-","-","-","-","-","-","-"]
jmasppholiveoncarkd     9180    ["apple","moon","jack","maven","hold","mark","spark","poor","solid","live"]     ["-","-","-","-","-","-","spark","-","-","-"]
mjasppholiveoarnckd     9252    ["apple","poor","maven","moon","mark","hold","jack","spark","solid","live"]     ["-","-","-","moon","-","-","-","-","-","-"]
sjmaphooarplidckven     9600    ["poor","hold","jack","maven","moon","mark","spark","apple","solid","live"]     ["poor","-","-","-","-","-","-","-","-","-"]
jmasppholivecoarkdn     9720    ["apple","jack","hold","maven","moon","mark","poor","spark","solid","live"]     ["-","-","-","-","-","mark","-","-","-","-"]
jmasppholiveaorckdn     9800    ["apple","spark","hold","moon","jack","maven","mark","poor","solid","live"]     ["-","-","-","-","-","-","mark","-","-","-"]
smhjapoplidveonarck     9936    ["solid","maven","moon","hold","mark","jack","spark","poor","apple","live"]     ["solid","-","-","-","-","jack","-","-","-","-"]
mshjapooplivencarkd     10080   ["moon","maven","jack","mark","spark","apple","solid","hold","poor","live"]     ["moon","-","-","-","-","-","-","hold","poor","-"]
mjasphooarckplivend     10080   ["poor","mark","maven","hold","moon","jack","apple","spark","solid","live"]     ["poor","mark","-","-","-","jack","-","-","-","-"]
jmasphooarckplivend     10080   ["poor","jack","maven","hold","moon","mark","apple","spark","solid","live"]     ["poor","jack","-","-","-","mark","-","-","-","-"]
shmjapoplidveaorckn     10400   ["solid","hold","apple","mark","maven","moon","jack","spark","poor","live"]     ["solid","-","apple","-","-","-","-","-","poor","-"]
hsjmapoplidcaorkven     10766   ["hold","jack","maven","mark","spark","poor","moon","apple","solid","live"]     ["hold","-","-","-","-","poor","-","-","-","-"]
smjaphooarplidvenck     11200   ["poor","hold","maven","moon","mark","jack","spark","apple","solid","live"]     ["poor","-","-","moon","-","-","-","-","-","-"]
jmasppholivedcaorkn     11200   ["apple","hold","jack","maven","moon","mark","spark","poor","solid","live"]     ["-","-","-","-","-","-","-","-","-","-"]
mhsjapooplivendcark     11232   ["moon","maven","hold","jack","mark","spark","poor","apple","solid","live"]     ["moon","-","-","-","-","-","poor","-","-","-"]
hmjaspoplidoarckven     11280   ["hold","mark","maven","moon","jack","poor","apple","spark","solid","live"]     ["hold","-","-","-","-","-","-","-","-","-"]
jmasppholivecoarknd     11336   ["apple","jack","maven","hold","moon","mark","poor","spark","solid","live"]     ["-","-","-","-","-","-","-","-","-","-"]
mjasphooplivencarkd     11520   ["moon","maven","jack","mark","poor","hold","apple","spark","solid","live"]     ["moon","-","-","-","poor","-","-","-","-","-"]
smhjapoplidaorckven     11760   ["solid","mark","maven","moon","hold","jack","spark","poor","apple","live"]     ["solid","-","-","-","-","-","-","-","-","-"]
hsmjapoplidveaorckn     11856   ["hold","apple","mark","maven","jack","spark","solid","moon","poor","live"]     ["hold","-","-","-","-","-","-","-","-","-"]
mjasppholiveoncarkd     12420   ["apple","maven","moon","jack","hold","mark","spark","poor","solid","live"]     ["-","-","moon","-","-","-","-","-","-","-"]
sjmaphooarckplidven     12720   ["poor","jack","hold","maven","moon","mark","spark","apple","solid","live"]     ["poor","-","-","-","-","-","-","-","-","-"]
smjaphooarplivendck     12960   ["poor","maven","hold","moon","mark","jack","spark","apple","solid","live"]     ["poor","-","-","-","-","-","-","-","-","-"]
mhjaspooplivendarck     13392   ["moon","maven","hold","mark","jack","poor","apple","spark","solid","live"]     ["moon","-","-","-","-","-","-","-","-","-"]
smjaphooarplidckven     13440   ["poor","hold","mark","maven","moon","jack","spark","apple","solid","live"]     ["poor","-","-","-","-","-","-","-","-","-"]
smjaphoplidoarvenck     13440   ["solid","poor","maven","hold","moon","mark","jack","spark","apple","live"]     ["solid","poor","-","-","moon","-","-","-","-","-"]
hmsjapoplidveonarck     13956   ["hold","maven","moon","mark","jack","spark","poor","apple","solid","live"]     ["hold","-","-","-","-","-","-","-","-","-"]
mjasppholivedoarckn     14000   ["apple","hold","mark","maven","moon","jack","poor","spark","solid","live"]     ["-","-","-","-","-","-","-","-","-","-"]
smhjapoplidovenarck     14112   ["solid","moon","maven","hold","mark","jack","spark","poor","apple","live"]     ["solid","moon","-","-","-","jack","-","-","-","-"]
mhsjapooplivencarkd     14400   ["moon","maven","jack","hold","mark","spark","poor","apple","solid","live"]     ["moon","-","-","-","-","-","-","-","-","-"]
hmjaspoplidveonarck     14844   ["hold","maven","moon","mark","jack","poor","apple","spark","solid","live"]     ["hold","-","-","-","-","-","-","-","-","-"]
mjasphooplivenardck     15552   ["moon","maven","poor","hold","mark","jack","apple","spark","solid","live"]     ["moon","-","-","-","-","-","-","-","-","-"]
mjasphooarplidvenck     15680   ["poor","hold","maven","moon","mark","jack","apple","spark","solid","live"]     ["poor","-","-","-","-","-","-","-","-","-"]
sjmaphooarckplivend     15680   ["poor","jack","maven","hold","moon","mark","spark","apple","solid","live"]     ["poor","-","-","-","-","mark","-","-","-","-"]
smjaphooarckplidven     16080   ["poor","mark","hold","maven","moon","jack","spark","apple","solid","live"]     ["poor","-","-","-","-","-","-","-","-","-"]
smjaphoplidovenarck     16128   ["solid","moon","maven","mark","jack","spark","poor","hold","apple","live"]     ["solid","moon","-","-","-","spark","-","-","-","-"]
msjaphooplivencarkd     18720   ["moon","maven","jack","mark","spark","poor","hold","apple","solid","live"]     ["moon","-","-","-","-","poor","-","-","-","-"]
jmasppholivecaorkdn     18840   ["apple","jack","hold","maven","moon","mark","spark","poor","solid","live"]     ["-","-","-","-","-","-","-","-","-","-"]
hsmjapoplidoarckven     19512   ["hold","mark","maven","jack","poor","moon","spark","apple","solid","live"]     ["hold","-","-","-","-","-","-","-","-","-"]
mjasppholivedaorckn     19600   ["apple","hold","mark","maven","moon","jack","spark","poor","solid","live"]     ["-","-","-","-","-","-","-","-","-","-"]
mshjapooplivenarckd     20160   ["moon","maven","mark","jack","spark","apple","solid","hold","poor","live"]     ["moon","-","-","-","-","-","-","hold","poor","-"]
jmasppholivecaorknd     20584   ["apple","jack","maven","hold","moon","mark","spark","poor","solid","live"]     ["-","-","-","-","-","mark","-","-","-","-"]
hmsjapoplidaorckven     20832   ["hold","mark","maven","moon","jack","spark","poor","apple","solid","live"]     ["hold","-","-","-","jack","-","-","-","-","-"]
mshjapooplivendarck     21168   ["moon","maven","apple","solid","hold","mark","jack","spark","poor","live"]     ["moon","-","-","-","-","-","-","-","poor","-"]
mjasppholiveoarckdn     21320   ["apple","mark","hold","maven","moon","jack","poor","spark","solid","live"]     ["-","-","-","-","-","-","-","-","-","-"]
shmjapoplidveonarck     21420   ["solid","maven","hold","moon","mark","jack","spark","poor","apple","live"]     ["solid","-","-","-","-","-","spark","-","-","-"]
smjaphoplidaorckven     22400   ["solid","mark","maven","moon","jack","spark","poor","hold","apple","live"]     ["solid","-","-","-","-","-","-","-","-","-"]
hmsjapoplidovenarck     22512   ["hold","moon","maven","mark","jack","spark","poor","apple","solid","live"]     ["hold","moon","-","-","-","-","-","-","-","-"]
mjasphooarplivendck     22752   ["poor","maven","hold","moon","mark","jack","apple","spark","solid","live"]     ["poor","-","-","moon","-","-","-","-","-","-"]
mjspappholiveonrckd     22788   ["maven","moon","mark","jack","spark","poor","apple","hold","solid","live"]     ["-","moon","-","-","-","-","apple","-","-","-"]
mjasppholivedonarck     22960   ["apple","hold","maven","moon","mark","jack","spark","poor","solid","live"]     ["-","-","-","moon","-","-","-","-","-","-"]
smjaphoplidoarckven     23040   ["solid","mark","maven","moon","jack","poor","hold","spark","apple","live"]     ["solid","-","-","-","-","-","-","-","-","-"]
msjaphooplivendarck     24192   ["moon","maven","apple","solid","mark","jack","spark","poor","hold","live"]     ["moon","-","-","-","-","-","-","-","hold","-"]
mjasppholiveoarcknd     24388   ["apple","mark","maven","hold","moon","jack","poor","spark","solid","live"]     ["-","-","-","-","-","jack","-","-","-","-"]
smjaphooarckplivend     24640   ["poor","mark","maven","hold","moon","jack","spark","apple","solid","live"]     ["poor","-","-","-","-","jack","-","-","-","-"]
smjaphooarplivenckd     24840   ["poor","maven","moon","mark","hold","jack","spark","apple","solid","live"]     ["poor","-","moon","-","-","-","-","-","-","-"]
jspmachoorkpplivedn     25200   ["jack","spark","mark","poor","apple","hold","maven","moon","solid","live"]     ["jack","-","-","-","-","-","-","moon","-","-"]
spjmahoorckpplivedn     25200   ["spark","jack","mark","poor","apple","hold","maven","moon","solid","live"]     ["spark","-","-","-","-","-","-","moon","-","-"]
smjaphoplidveonarck     25344   ["solid","maven","moon","mark","jack","spark","poor","hold","apple","live"]     ["solid","-","-","-","-","spark","-","-","-","-"]
mjasphooarplivenckd     25848   ["poor","maven","moon","mark","hold","jack","apple","spark","solid","live"]     ["poor","-","-","-","-","-","-","-","-","-"]
mjspahoppliveondrck     25920   ["maven","hold","moon","mark","jack","spark","poor","apple","solid","live"]     ["maven","-","-","-","-","-","-","-","-","-"]
mjspahoppliveondcrk     25920   ["maven","hold","moon","jack","mark","spark","poor","apple","solid","live"]     ["maven","-","-","-","-","-","-","-","-","-"]
mjspahoppliveonrckd     25920   ["maven","moon","mark","hold","jack","spark","poor","apple","solid","live"]     ["maven","-","-","-","-","-","-","-","-","-"]
mjasppholiveondarck     25968   ["apple","maven","hold","moon","mark","jack","spark","poor","solid","live"]     ["-","-","-","-","-","-","-","-","-","-"]
shmjapoplidaorckven     26320   ["solid","hold","mark","maven","moon","jack","spark","poor","apple","live"]     ["solid","-","-","-","-","-","-","-","-","-"]
mjspappholiveoncrkd     26460   ["maven","moon","jack","mark","spark","poor","apple","hold","solid","live"]     ["-","moon","-","-","-","-","apple","-","-","-"]
hsmjapoplidveonarck     27900   ["hold","maven","mark","jack","spark","poor","moon","apple","solid","live"]     ["hold","-","-","-","-","poor","-","-","-","-"]
mjasppholiveaorckdn     29440   ["apple","mark","hold","maven","moon","jack","spark","poor","solid","live"]     ["-","-","-","-","-","-","-","-","-","-"]
mjspahoorckpplivedn     30240   ["mark","jack","spark","poor","apple","hold","maven","moon","solid","live"]     ["mark","-","-","-","-","-","-","moon","-","-"]
mspjahoorckpplivedn     30240   ["mark","spark","jack","poor","apple","hold","maven","moon","solid","live"]     ["mark","-","-","-","-","-","-","moon","-","-"]
mhsjapooplivendarck     31968   ["moon","maven","hold","mark","jack","spark","poor","apple","solid","live"]     ["moon","-","-","-","-","-","-","-","-","-"]
mhsjapooplivenarckd     33120   ["moon","maven","mark","hold","jack","spark","poor","apple","solid","live"]     ["moon","-","-","-","jack","-","-","-","-","-"]
mjasppholiveaorcknd     33392   ["apple","mark","maven","hold","moon","jack","spark","poor","solid","live"]     ["-","-","-","-","-","jack","-","-","-","-"]
mjasphooplivenarckd     33408   ["moon","maven","mark","jack","poor","hold","apple","spark","solid","live"]     ["moon","-","-","-","-","-","-","-","-","-"]
mjspahoppliveoncrkd     34560   ["maven","moon","jack","hold","mark","spark","poor","apple","solid","live"]     ["maven","-","jack","-","-","-","-","-","-","-"]
jmspachoorkpplivedn     35280   ["jack","mark","spark","poor","apple","hold","maven","moon","solid","live"]     ["jack","-","-","-","-","-","-","moon","-","-"]
spmjahoorckpplivedn     35280   ["spark","mark","jack","poor","apple","hold","maven","moon","solid","live"]     ["spark","-","-","-","-","-","-","moon","-","-"]
hsmjapoplidaorckven     37968   ["hold","mark","maven","jack","spark","poor","moon","apple","solid","live"]     ["hold","-","-","-","-","poor","-","-","-","-"]
jspmachoorkpplidven     45360   ["jack","hold","moon","spark","maven","mark","poor","apple","solid","live"]     ["jack","-","-","-","-","-","-","-","-","-"]
spjmahoorckpplidven     45360   ["spark","hold","moon","jack","maven","mark","poor","apple","solid","live"]     ["spark","-","-","-","-","-","-","-","-","-"]
mjasppholiveonarckd     48924   ["apple","maven","moon","mark","hold","jack","spark","poor","solid","live"]     ["-","-","moon","-","-","-","-","-","-","-"]
jspmachoorkpplivend     50400   ["jack","moon","hold","spark","maven","mark","poor","apple","solid","live"]     ["jack","-","-","-","-","mark","-","-","-","-"]
spjmahoorckpplivend     50400   ["spark","moon","hold","jack","maven","mark","poor","apple","solid","live"]     ["spark","-","-","-","-","mark","-","-","-","-"]
mspjahoppliveondrck     51840   ["maven","hold","moon","mark","spark","jack","poor","apple","solid","live"]     ["maven","-","-","-","-","-","-","-","-","-"]
mspjappholiveonrckd     51840   ["maven","moon","mark","spark","jack","poor","apple","hold","solid","live"]     ["-","moon","-","-","-","-","-","-","-","-"]
mspjahoppliveonrckd     60480   ["maven","moon","mark","hold","spark","jack","poor","apple","solid","live"]     ["maven","-","-","-","-","-","-","-","-","-"]
mjspahoorckpplidven     60480   ["mark","hold","maven","moon","jack","spark","poor","apple","solid","live"]     ["mark","-","-","-","-","-","-","-","-","-"]
mspjahoorckpplidven     60480   ["mark","hold","maven","moon","spark","jack","poor","apple","solid","live"]     ["mark","-","-","-","-","-","-","-","-","-"]
msjaphooplivenarckd     63360   ["moon","maven","mark","jack","spark","poor","hold","apple","solid","live"]     ["moon","-","-","-","-","poor","-","-","-","-"]
jmspachoorkpplidven     75600   ["jack","hold","maven","moon","mark","spark","poor","apple","solid","live"]     ["jack","-","-","-","-","-","-","-","-","-"]
spmjahoorckpplidven     75600   ["spark","hold","maven","moon","mark","jack","poor","apple","solid","live"]     ["spark","-","-","-","-","-","-","-","-","-"]
mjspahoorckpplivend     90720   ["mark","maven","hold","moon","jack","spark","poor","apple","solid","live"]     ["mark","-","-","-","jack","spark","-","-","-","-"]
mspjahoorckpplivend     90720   ["mark","maven","hold","moon","spark","jack","poor","apple","solid","live"]     ["mark","-","-","-","spark","jack","-","-","-","-"]
jmspachoorkpplivend     131040  ["jack","maven","hold","moon","mark","spark","poor","apple","solid","live"]     ["jack","-","-","-","mark","spark","-","-","-","-"]
spmjahoorckpplivend     131040  ["spark","maven","hold","moon","mark","jack","poor","apple","solid","live"]     ["spark","-","-","-","mark","jack","-","-","-","-"]

 */